extreme-startup/questionator

- .github/PULL_REQUEST_TEMPLATE.md
https://github.com/extreme-startup/questionator/issues/5
> docs: Add default PR template

- client/package-lock.json
- client/package.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/main.ts
prepared project for heroku deployments
- [ x] Changes follow our guidelines: [TODO: link to CONTRIBUTING.md]()
```
[ ] Bugfix
[ ] Feature
[x ] Build related changes
```
> [TF] Setup environments #17

- CONTRIBUTING.MD
```
[ ] Bugfix
[ ] Feature
[x] Other: CONTRIBUTING.md added
[Issue Number:](https://github.com/extreme-startup/extreme-startup.github.io/issues/16)
> CONTRIBUTING.md added

- client/package-lock.json
- client/package.json
- client/src/common/styledComponents/Button.js
- client/src/common/styledComponents/Title.js
- client/src/common/styledComponents/index.js
- client/src/components/Trainings.vue
- client/src/views/Home.vue
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Issue Number: #42 
- Implement Vue Styled Components and change pre-commit hooks to pre-push
- Add Trainings components
> Vue styled components

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.MD
```
[ ] Bugfix
[ ] Feature
[x] Doc changes
```
Move contributing process to GitHub wiki. Remove duplication from CONTRIBUTION.md.
Add link to guidelines in PULL_REQUEST_TEMPLATE.md
> Move contributing process to github wiki

- client/package-lock.json
- client/package.json
- client/src/App.vue
- client/src/common/styledComponents/Button.js
- client/src/common/styledComponents/Header.js
- client/src/common/styledComponents/List.js
- client/src/common/styledComponents/Section.js
- client/src/common/styledComponents/Serach.js
- client/src/common/styledComponents/Title.js
- client/src/common/styledComponents/index.js
- client/src/components/Header.vue
- client/src/components/Sessions.vue
- client/src/components/Trainings.vue
- client/src/views/Home.vue
- scripts/allowedLicenses.json
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] CI related changes
Adding template for Landing/Home Page. Add reset-css. Allow unlicense libraries
Issue Number: #32
> Landing home page

- server/src/app.module.ts
- server/src/entity/Contest.ts
- server/src/migration/1553696191989-ContestMigration.ts
- server/src/modules/Contest/__mocks__/mocks.ts
- server/src/modules/Contest/contest.controller.spec.ts
- server/src/modules/Contest/contest.controller.ts
- server/src/modules/Contest/contest.interface.ts
- server/src/modules/Contest/contest.module.ts
- server/src/modules/Contest/contest.service.spec.ts
- server/src/modules/Contest/contest.service.ts
```
[ ] Bugfix
[x] Feature
```
Added endpoints to execute CRUD operations for contest entity
Issue Number: 22
> feat(22): Add CRUD endpoints for contest

- server/src/app.module.ts
- server/src/entity/Question.ts
- server/src/entity/Questions.ts
- server/src/migration/1553647346431-QuestionMigration.ts
- server/src/modules/Question/dto/question.dto.ts
- server/src/modules/Question/question.controller.spec.ts
- server/src/modules/Question/question.controller.ts
- server/src/modules/Question/question.module.ts
- server/src/modules/Question/question.service.spec.ts
- server/src/modules/Question/question.service.ts
```
[ ] Bugfix
[x] Feature
```
Its a PR for [FEATURE_23(BE)](https://github.com/extreme-startup/questionator/issues/23)
```
GET /question  - get all questions
GET /question/:id - get question by id
POST /question  - add new question
PUT /question/:id - update question 
DELETE /question - delete question
> feat(23): adding question BE

- client/package.json
- client/src/common/styledComponents/Button.js
- client/src/competition/competition-details-modal/CompetitionDetailsModal.style.js
- client/src/competition/competition-details-modal/CompetitionDetailsModal.vue
- client/src/competition/competition-details-modal/Modal.style.js
- client/src/competition/competition-details-modal/__tests__/competition-details-validation.spec.js
- client/src/competition/competition-details-modal/competition-details-validation.js
- client/src/competition/competition-details.model.js
- client/src/components/Trainings.vue
- server/src/modules/Contest/contest.controller.spec.ts
- server/src/modules/Contest/contest.controller.ts
- server/src/modules/Contest/contest.service.spec.ts
```
[ ] Bugfix
[x] Feature
[x] CI related changes
```
[#22](https://github.com/extreme-startup/questionator/issues/22)
Issue Number: 22
> feat(22): [FE] Create competition

- client/src/api/auth.js
- client/src/router.js
- server/src/modules/User/user.controller.spec.ts
- server/src/modules/User/user.controller.ts
- server/src/modules/User/user.service.spec.ts
- server/src/modules/User/user.service.ts
```
[ ] Bugfix
[ ] Feature
```
> Bugfix add user info endpoint

- client/src/components/LoginForm.vue
```
[ ] Bugfix
[ ] Feature
```
> style-add-mock-class-for-test

- client/package.json
- package.json
- server/package.json
```
[ ] Bugfix
[ ] Feature
[x ] CI related changes
```
Added coverage threshold check. 
Minimal coverage values set from the current code coverage
Issue Number: 40
> feat(#40): Added coverage threshold check

- package-lock.json
- package.json
- server/src/main.ts
details: https://github.com/bripkens/connect-history-api-fallback#introduction
```
[ ] Bugfix
[ ] Feature
```
> fix(00): SPA-backend routing collision

- client/src/router.js
```
[ ] Bugfix
[ ] Feature
```
> bugfix-remove-navigation-if-user-not-logged-in

- client/package.json
- client/src/common/styledComponents/List.js
- client/src/components/Trainings.vue
- server/src/main.ts
```
[ ] Bugfix
[x] Feature
```
Deletion of a competition
Issue Number: 34
> Feat contest

- server/src/entity/AskedQuestion.ts
- server/src/migration/1554142210463-AskedQuestion.ts
```
[ ] Bugfix
[x] Feature
```
Add new class implementing asked question entity for DB
Issue Number: #43
> Add asked question class for BD

- client/package-lock.json
- client/package.json
- client/src/App.vue
- client/src/api/question.js
- client/src/common/Modal.vue
- client/src/common/Select.vue
- client/src/common/__tests__/Modal.spec.js
- client/src/common/__tests__/Select.spec.js
- client/src/common/__tests__/__snapshots__/Modal.spec.js.snap
- client/src/common/__tests__/__snapshots__/Select.spec.js.snap
- client/src/common/mixins/__tests__/TestComponent.vue
- client/src/common/mixins/__tests__/toggle.spec.js
- client/src/common/mixins/toggle.js
- client/src/components/AddQuestion.vue
- client/src/components/QuestionForm.vue
- client/src/components/QuestionTab.vue
- client/src/components/__tests__/AddQuestion.spec.js
- client/src/components/__tests__/QestionForm.spec.js
- client/src/components/__tests__/__snapshots__/AddQuestion.spec.js.snap
- client/src/components/__tests__/__snapshots__/QestionForm.spec.js.snap
- client/src/store/index.js
- client/src/store/question.js
- package-lock.json
- server/package-lock.json
- server/src/entity/Question.ts
- server/src/migration/1553936929517-SetQuestionIsDeletedDefaultValue.ts
- server/src/modules/Question/question.controller.ts
```
[ ] Bugfix
[ ] Feature
```
> Feat 23/add new question ui

- server/src/main.ts
```
[ ] Bugfix
[ ] Feature
```
> Fixed history-api-fallback to bypass swagger urls

- client/src/components/Trainings.vue
```
[ ] Bugfix
[ ] Feature
```
> feat(#22): Remove redundant alert

- client/src/components/DataTable.vue
- client/src/components/QuestionForm.vue
- client/src/components/__tests__/__snapshots__/AddOrEditQuestion.spec.js.snap
- client/src/components/__tests__/__snapshots__/QuestionForm.spec.js.snap
- client/src/views/Training.vue
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Add question error ids for testing. Use buttons from components library.
> refactor(0): Add question error ids for testing. 

- client/package-lock.json
- client/package.json
- client/src/components/QuestionTab.vue
- client/src/components/TabbedPanel.vue
- client/src/views/Home.vue
- client/src/views/Training.vue
```
[x] Bugfix
[ ] Feature
```
Removed fragments because selenide mark all elements inside <Fragment> as invisible.
> fix(0): Removed fragments for selenide.

- client/src/components/AddOrEditQuestion.vue
- client/src/components/QuestionForm.vue
- client/src/components/__tests__/QuestionForm.spec.js
- client/src/components/__tests__/__snapshots__/AddOrEditQuestion.spec.js.snap
- client/src/components/__tests__/__snapshots__/QuestionForm.spec.js.snap
- client/src/store/form.js
```
[ ] Bugfix
[ ] Feature
```
> fix(#96) Fix value field validation

- server/src/migration/1555064588740-ManageSessionEntity.ts
- server/src/modules/manage-session/ManageSession.dto.ts
- server/src/modules/manage-session/manage-session.controller.spec.ts
- server/src/modules/manage-session/manage-session.service.spec.ts
- server/src/modules/manage-session/manage-session.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fix session manage migration.
Issue Number: #55
> Fix(#55) manage session fix migration

- server/src/modules/Contest/contest.service.spec.ts
- server/src/modules/Contest/contest.service.ts
```
[ ] Bugfix
[x] Feature
```
> feat(0000): add filtering of deleted questions

- client/src/competition/competition-details-modal/CompetitionDetailsModal.style.js
- client/src/competition/competition-details-modal/CompetitionDetailsModal.vue
- client/src/competition/competition-details-modal/Modal.style.js
- client/src/components/DeleteQuestion.vue
- client/src/components/LoginForm.vue
- client/src/components/Trainings.vue
- client/src/sessions/ManageSession.vue
- client/src/store/question.js
```
[x] Bugfix
[ ] Feature
```
> Fix(#101): Create competitions styling issues

- client/src/contenders/ContendersTable.vue
- client/src/contenders/api.js
- client/src/sessions/ActiveSession.vue
- client/src/sessions/ManageSessionTable.vue
- client/src/sessions/api.js
- client/src/store/contenders.js
- client/src/store/index.js
- client/src/store/session.js
- server/src/modules/manage-session/ManageSession.dto.ts
```
[ ] Bugfix
[x] Feature
```
At the workshop page when click on the session-corresponent row nothing happens / A pop-up is opened (see the screenshot below)
Issue Number: #55
> Add active session pop-up, contensers table and correspondent actions

- client/package-lock.json
- client/package.json
- client/src/common/Modal.vue
- client/src/common/__tests__/__snapshots__/Modal.spec.js.snap
- client/src/components/AddOrEditQuestion.vue
- client/src/components/DataTable.vue
- client/src/components/QuestionForm.vue
- client/src/components/QuestionTab.vue
- client/src/components/__tests__/__snapshots__/AddOrEditQuestion.spec.js.snap
- client/src/components/__tests__/__snapshots__/QuestionForm.spec.js.snap
- client/src/main.js
- client/src/sessions/ManageSession.vue
```
[ ] Bugfix
[ ] Feature
```
> update question table and form with Vuetify

- server/src/migration/1555619727302-AskedQuestion.ts
- [x ] Changes follow our [guidelines](https://github.com/extreme-startup/questionator/wiki/Contributing)
```
[ x] Bugfix
[ ] Feature
```
migration fixing
> FEAT-56: fixing migration

- client/src/components/DataTable.vue
```
[ ] Bugfix
[ ] Feature
```
> add ids on edit and delete buttons for testing

- client/src/competition/competition-data.service.js
- client/src/competition/competition-details-modal/CompetitionDetailsModal.vue
- client/src/competition/confirm-competition-delete-modal/ConfirmCompetitionDeleteModal.vue
- client/src/components/Trainings.vue
- client/src/sessions/ActiveSession.vue
- client/src/sessions/ManageSession.vue
- client/src/sessions/ManageSessionTable.vue
- server/src/modules/Contest/contest.service.spec.ts
- server/src/modules/Contest/contest.service.ts
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Issue Number: 102
> Fix 102 competition deletion handling

- server/package.json
- server/src/models/response.dto.ts
- server/src/modules/Question/dto/answer.dto.ts
- server/src/modules/Question/dto/question.dto.ts
- server/src/modules/Question/helpers/questions.helper.ts
- server/src/modules/Question/question.controller.ts
- server/src/modules/Question/question.service.ts
```
[ ] Bugfix
[ ] Feature
```
> Fix questions module

- server/src/modules/Contest/contest.controller.spec.ts
- server/src/modules/Contest/contest.controller.ts
- server/src/modules/Contest/contest.dto.ts
- server/src/modules/Contest/contest.service.spec.ts
- server/src/modules/Contest/contest.service.ts
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Refactoring of the Contest module due to global updates of the DB
> fix(#132): Contest module db update fix

- client/src/components/QuestionTab.vue
- client/src/components/TabbedPanel.vue
- client/src/views/Training.vue
```
[ ] Bugfix
[ ] Feature
```
> feat: replace tabs with vuetify component

- client/src/api/question.js
- server/src/modules/Contest/contest.module.ts
- server/src/modules/Contest/contest.service.ts
- server/src/modules/Question/dto/question.dto.ts
- server/src/modules/Question/question.module.ts
- server/src/modules/Question/question.service.ts
- [-] Changes follow our [guidelines](https://github.com/extreme-startup/questionator/wiki/Contributing)
- [-] Tests for the changes have been added
- [-] Docs have been added / updated
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: crutch
```
Issue Number: 131
New DB structure seems wrong and overengineered but who cares.
> Migrate Question module to new DB structure. #131

- client/package.json
- client/src/components/Sessions.vue
- client/src/contest-session/ActiveSession.vue
- client/src/contest-session/ContendersTable.vue
- client/src/contest-session/ContestSession.vue
- client/src/contest-session/LeaderBoard.vue
- client/src/contest-session/api.js
- client/src/store/contest-session.js
- client/src/store/index.js
- server/src/modules/ContestSession/contest-session.service.ts
```
[ ] Bugfix
[ ] Feature
```
> make contest session load

- client/package-lock.json
- server/package-lock.json
```
[ ] Bugfix
[ ] Feature
```
> fix package lock registry

- server/src/modules/AskQuestions/ask-questions.service.ts
- server/src/modules/Contender/contender.gateway.ts
- server/src/modules/ContestSession/contest-session.service.ts
- server/src/modules/Player/player.service.ts
- server/src/modules/Question/question.service.spec.ts
- server/src/modules/Question/question.service.ts
```
[ ] Bugfix
[ ] Feature
```
> add player and contest refs to asked question

- README.md
```
[ ] Bugfix
[ ] Feature
```
> add tip to start local app

- server/src/modules/AskQuestions/ask-questions.service.ts
```
[ ] Bugfix
[ ] Feature
```
> remove unsubscibe from answer subject

- client/src/components/Trainings.vue
- server/src/modules/Contest/contest.controller.spec.ts
- server/src/modules/Contest/contest.controller.ts
- server/src/modules/Contest/contest.module.ts
- server/src/modules/Contest/contest.service.spec.ts
- server/src/modules/Contest/contest.service.ts
```
[x] Bugfix
[ ] Feature
```
> Fix(#26): Add setting of users id on when contest is created

- client/src/contest-session/ContestSession.vue
- client/src/store/contest-session.js
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
redirect to the session after creating new one
> navigate to contest session after it is created

- server/src/modules/AskQuestions/ask-questions.service.ts
- server/src/modules/Question/question.service.ts
```
[x] Bugfix
[x] Feature
```
Incorrect answers and errors from a contender are handled
> Handle player score
